[versions]
kotlin = "2.3.10"
ksp = "2.3.5"
kotlinx-serialization = "1.10.0"
buildconfig = "6.0.7"
shadow = "9.3.1"
dokka = "2.1.0"
publishing-plugin = "0.36.0"
coroutines = "1.10.2"
junit = "6.0.3"
mockk = "1.14.9"
slf4j = "2.0.17"
sweet-spi = "0.1.3"
kcp-development = "0.0.2"

[libraries]
ksp-api = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "ksp" }
kotlinx-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlinx-serialization" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
slf4j = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
buildconfig = { id = "com.github.gmazzo.buildconfig", version.ref = "buildconfig" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
sweet-spi = { id = "dev.whyoleg.sweetspi", version.ref = "sweet-spi" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kotlin-power-assert = { id = "org.jetbrains.kotlin.plugin.power-assert", version.ref = "kotlin" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
publishing = { id = "com.vanniktech.maven.publish", version.ref = "publishing-plugin" }

kcp-dev-compiler = { id = "dev.rnett.kcp-development.compiler-plugin", version.ref = "kcp-development" }
kcp-dev-gradle = { id = "dev.rnett.kcp-development.gradle-plugin", version.ref = "kcp-development" }